bio:
  name: Dimas Ananda Putra Perdana
  location: Central Java, Indonesia
  role: Developer
  description: "Hey!👋 Welcome to my profile. Nice to meet you! I'm Dimanda, I'm an independent developer with 3+ years of experience. In the realm of engineering, my ardor lies within the captivating realms of web development, the Internet of Things, electronics, and the ethereal domain of physics. Apart from the engineering world, I am passionate about nature. In my spare time, I indulge my passion for nature by immersing myself in the enchanting depths of the jungle."
  imgUrl: https://avatars.githubusercontent.com/u/52043756